server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800
  port: 8080

jwt:
  secret: c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK

spring:
  default-encoding: utf-8


  messages:
    basename: messages, errors

  profiles:
    active: local

  redis:
    host: localhost
    port: 6379


  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/liveamonth?serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update #자동으로 테이블 생성
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: true # db 커넥션을 트랜잭션에서만 하고 끝냄..

  mail:
    host: smtp.gmail.com
    port: 587
    username: tp.liveamonth@gmail.com
    password: qsjriazlimmitdir
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        mime:
          charset: UTF-8
        transport:
          protocol: smtp
        debug: false


logging:
  level:
    org.hibernate.SQL: debug # 하이버네이트가 생성하는 SQL이 다보인다.