spring:

  config:
    import: classpath:database.yml, classpath:oauth2.yml
  profiles:
    include:
      - database
      - ouath2

  messages:
    basename: messages, errors, initdb

  mail:
    host: smtp.gmail.com
    port: 587
    username: tp.liveamonth@gmail.com
    password: qsjriazlimmitdir
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        mime:
          charset: UTF-8
        transport:
          protocol: smtp
        debug: false


logging:
  level:
    org.hibernate.SQL: debug # 하이버네이트가 생성하는 SQL이 다보인다.
